# Generated by Django 4.2.25 on 2025-10-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly base salary in NPR', max_digits=10),
        ),
    ]
