# Generated by Django 4.2.25 on 2025-10-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_employee_monthly_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Approved Leave', 'Approved Leave')], default='Present', max_length=15),
        ),
    ]
