# Generated by Django 4.2.25 on 2025-11-12 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='completed_tasks',
            field=models.TextField(blank=True, help_text='Tasks completed (check-out)', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='todo_tasks',
            field=models.TextField(blank=True, help_text='Tasks to do for the day (check-in)', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=10),
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('todo', 'To-Do'), ('completed', 'Completed')], max_length=10)),
                ('image', models.ImageField(upload_to='task_attachments/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attachments', to='attendance.attendance')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
