# Generated by Django 4.2.25 on 2025-11-14 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0009_attendance_completed_tasks_attendance_todo_tasks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False, help_text='Admin approval status')),
                ('admin_comment', models.TextField(blank=True, help_text="Admin's feedback on completed tasks", null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Has employee read the feedback?')),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_feedback', to='attendance.attendance')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Feedback',
                'verbose_name_plural': 'Task Feedbacks',
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
